### ISSUE TITLE
Segfault when using the --add-event flag

### ISSUE THREAD

**Issue by AnaGelez** [elementary/calendar#421]
Hello! I tried to add an event from command line with `io.elementary.calendar --add-event`, and I got this error:

```
(io.elementary.calendar:6313): e-data-server-CRITICAL **: 12:51:47.205: e_source_registry_list_sources: assertion 'E_IS_SOURCE_REGISTRY (registry)' failed

(io.elementary.calendar:6313): GLib-GObject-CRITICAL **: 12:51:47.205: g_object_get: assertion 'G_IS_OBJECT (object)' failed
fish : Tâche , 'io.elementary.calendar --add-ev…' terminée par le signal SIGSEGV (Erreur de frontière d'adresse)
```

Here is the backtrace I get in GDB, if it helps:

<details>
<summary>Backtrace</summary>

```
#0  0x00007ffff739bcc1 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff739e56b in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff739e939 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00005555555936d2 in  ()
#4  0x00007ffff739c57e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff739dee5 in g_object_new_with_properties () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff739e961 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x0000555555573809 in maya_view_event_edition_info_panel_construct ()
#8  0x000055555556f3ee in maya_view_event_dialog_construct ()
#9  0x000055555556d6ca in maya_main_window_on_tb_add_clicked ()
#10 0x000055555556c3b0 in  ()
#11 0x00007ffff739710d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff73a9de8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff73b2715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff73b312f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff6e07b95 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007ffff6e07da6 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x000055555556c7e8 in maya_main ()
#18 0x00007ffff404cb97 in __libc_start_main (main=0x555555569770 <main>, argc=2, argv=0x7fffffffe1c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe1b8) at ../csu/libc-start.c:310
#19 0x00005555555697aa in _start ()
```
</details>

**Comment by Thalexander** [comment]
The registry in the calendar model is loaded asynchronously, when the model is initiated by the info panel the registry is still null, loading sources fails and then in constructing the CalendarButton it errors. This can be avoided by waiting for Idle before triggering the loading of the dialog.
