### ISSUE TITLE
gettext-template Actions keeps failing

### ISSUE THREAD

**Issue by ryonakano** [elementary/calendar#584]
See https://github.com/elementary/calendar/runs/996656577:

```
Successfully build the project!

Traceback (most recent call last):
  File "/check-diff.py", line 63, in <module>
    commit_to_repo(repo)
  File "/check-diff.py", line 21, in commit_to_repo
    raise NameError('Unable to push to repository: ' + error_msg)
NameError: Unable to push to repository: [remote rejected] (protected branch hook declined)

Checking the repository for new translations...
po/extra/extra.pot has changed!
There are translation changes, committing changes to repository!
```

**Comment by ryonakano** [comment]
Seems like fixed

**Comment by danrabbit** [comment]
Only temporarily. I really don't know what the actual cause of the issue is. There's some kind of permission issue. Reopening

**Comment by ryonakano** [comment]
It seems to work consistently so maybe we can close this issue? :thinking:
