### ISSUE TITLE
Calendar crashes on opening

### ISSUE THREAD

**Issue by jcamposz** [elementary/calendar#644]
In Odin 6 I need to execute many times Calendar ,it crashes frequently on opening . After three or four times it normally opens.
I've debugged the crashed and I've obtained:

#0  0x00007fe4b70e724c in  () at /lib/x86_64-linux-gnu/libelementary-calendar.so.0
#1  0x00007fe4b7022ab0 in g_slist_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fe4b70e5da3 in  () at /lib/x86_64-linux-gnu/libelementary-calendar.so.0
#3  0x00007fe4b6e97db3 in g_cclosure_marshal_VOID__POINTERv ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007fe4b6e94a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fe4b6eb3b28 in g_signal_emit_valist ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fe4b6eb40d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fe4b62dff00 in  () at /lib/x86_64-linux-gnu/libecal-2.0.so.1
#8  0x00007fe4b7002e8e in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007fe4b7003240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fe4b70032e3 in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fe4b6415fd5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x000055dce17b61c8 in maya_main ()
#13 0x00007fe4b5ca20b3 in __libc_start_main (main=
    0x55dce17b21c0 <main>, argc=1, argv=0x7ffc080efc78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc080efc68) at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {94407164309936, -6118381962410440533, 94407164109280, 140720443686000, 0, 0, 6120167698006427819, 6115412831737235627}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffc080efc78}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#14 0x000055dce17b220e in _start ()

**Comment by mcclurgm** [comment]
Thanks for the report. I think we'll need a little more info though. If you can get this to happen again, can you copy the full message? It may say something like "segmentation fault," which would be useful to know.

**Comment by jcamposz** [comment]
Helllo @mcclurgm when it crashes : Violación de segmento (`core' generado)
and using gdb with bt full option:

[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
El núcleo se generó por «io.elementary.calendar».
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f97d481924c in ?? () from /lib/x86_64-linux-gnu/libelementary-calendar.so.0
[Current thread is 1 (Thread 0x7f97c9571cc0 (LWP 4996))]
(gdb) bt full
#0  0x00007f97d481924c in  () at /lib/x86_64-linux-gnu/libelementary-calendar.so.0
#1  0x00007f97d4754ab0 in g_slist_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f97d4817da3 in  () at /lib/x86_64-linux-gnu/libelementary-calendar.so.0
#3  0x00007f97d45c9db3 in g_cclosure_marshal_VOID__POINTERv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007f97d45c6a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f97d45e5b28 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f97d45e60d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f97d3a11f00 in  () at /lib/x86_64-linux-gnu/libecal-2.0.so.1
#8  0x00007f97d4734e8e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007f97d4735240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f97d47352e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f97d3b47fd5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x000055a03054c1c8 in maya_main ()
#13 0x00007f97d33d40b3 in __libc_start_main (main=
    0x55a0305481c0 <main>, argc=1, argv=0x7ffd44d330c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd44d330b8) at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {94146494173616, 1342436393539350335, 94146493972960, 140725758144704, 0, 0, -1343265178879774913, -1328864586170486977}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffd44d330c8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#14 0x000055a03054820e in _start ()

**Comment by mcclurgm** [comment]
So it is a segmentation fault, thanks for adding that! I'd appreciate if you could do one more thing. Could you run `valgrind io.elementary.calendar` and paste the results? We should only need the last few paragraphs of the output, or you could put it in a gist. (I expect it'll be a really long output)

**Comment by jcamposz** [comment]
Here it is:

==17273== Conditional jump or move depends on uninitialised value(s)
==17273==    at 0x21E7F13E: ??? (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.47.0)
==17273==    by 0x21E75595: rsvg_rust_handle_get_pixbuf_sub (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.47.0)
==17273==    by 0x21D55485: ??? (in /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so)
==17273==    by 0x542CAA2: gdk_pixbuf_loader_close (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==17273==    by 0x5429232: ??? (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==17273==    by 0x542A24E: gdk_pixbuf_new_from_stream_at_scale (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==17273==    by 0x4D7D718: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273==    by 0x4D80A97: gtk_icon_info_load_icon (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273==    by 0x4D79D11: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273==    by 0x4D7A437: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273==    by 0x4D7A553: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273==    by 0x4D7A69F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==17273== 
==17273== Invalid read of size 8
==17273==    at 0x486E24C: ??? (in /usr/lib/x86_64-linux-gnu/libelementary-calendar.so.0.1)
==17273==    by 0x48EFAAF: g_slist_foreach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x486CDA2: ??? (in /usr/lib/x86_64-linux-gnu/libelementary-calendar.so.0.1)
==17273==    by 0x4A8FDB2: g_cclosure_marshal_VOID__POINTERv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4A8CA55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4AABB27: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4AAC0D2: g_signal_emit (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x5655EFF: ??? (in /usr/lib/x86_64-linux-gnu/libecal-2.0.so.1.0.0)
==17273==    by 0x48CFE8D: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x48D023F: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x48D02E2: g_main_context_iteration (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x5526FD4: g_application_run (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.6400.3)
==17273==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==17273== 
==17273== 
==17273== Process terminating with default action of signal 11 (SIGSEGV)
==17273==  Access not within mapped region at address 0x0
==17273==    at 0x486E24C: ??? (in /usr/lib/x86_64-linux-gnu/libelementary-calendar.so.0.1)
==17273==    by 0x48EFAAF: g_slist_foreach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x486CDA2: ??? (in /usr/lib/x86_64-linux-gnu/libelementary-calendar.so.0.1)
==17273==    by 0x4A8FDB2: g_cclosure_marshal_VOID__POINTERv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4A8CA55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4AABB27: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x4AAC0D2: g_signal_emit (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3)
==17273==    by 0x5655EFF: ??? (in /usr/lib/x86_64-linux-gnu/libecal-2.0.so.1.0.0)
==17273==    by 0x48CFE8D: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x48D023F: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x48D02E2: g_main_context_iteration (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3)
==17273==    by 0x5526FD4: g_application_run (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.6400.3)
==17273==  If you believe this happened as a result of a stack
==17273==  overflow in your program's main thread (unlikely but
==17273==  possible), you can try to increase the size of the
==17273==  main thread stack using the --main-stacksize= flag.
==17273==  The main thread stack size used in this run was 8388608.
==17273== 
==17273== HEAP SUMMARY:
==17273==     in use at exit: 16,229,545 bytes in 197,542 blocks
==17273==   total heap usage: 4,354,196 allocs, 4,156,654 frees, 230,924,525 bytes allocated
==17273== 
==17273== LEAK SUMMARY:
==17273==    definitely lost: 98,328 bytes in 132 blocks
==17273==    indirectly lost: 113,243 bytes in 4,757 blocks
==17273==      possibly lost: 1,337,656 bytes in 4,932 blocks
==17273==    still reachable: 12,925,326 bytes in 176,076 blocks
==17273==                       of which reachable via heuristic:
==17273==                         length64           : 21,448 bytes in 301 blocks
==17273==                         newarray           : 3,056 bytes in 111 blocks
==17273==         suppressed: 0 bytes in 0 blocks
==17273== Rerun with --leak-check=full to see details of leaked memory
==17273== 
==17273== Use --track-origins=yes to see where uninitialised values come from
==17273== For lists of detected and suppressed errors, rerun with: -s
==17273== ERROR SUMMARY: 2624 errors from 376 contexts (suppressed: 2 from 2)
Violación de segmento

**Comment by mcclurgm** [comment]
Alright. Sorry but I have one more thing for you to do. You need to get a version of Calendar that has debug symbols included, so we can find where in the code things are going wrong. Here's a link that tells you how to do it: https://wiki.ubuntu.com/DebuggingProgramCrash#Installing_dbgsym_packages_from_a_PPA
If you can do that and reproduce the crash in Valgrind again, that would be great!

**Comment by jcamposz** [comment]
Sorry for the delay. I've executed using valgrind:
odiseo@odiseo-SLIMBOOK:/etc/apt/sources.list.d$ valgrind io.elementary.calendar 
==67618== Memcheck, a memory error detector
==67618== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==67618== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==67618== Command: io.elementary.calendar
==67618== 
Gtk-Message: 08:10:46.150: Failed to load module "pantheon-filechooser-module"
--67618-- WARNING: unhandled amd64-linux syscall: 315
--67618-- You may be able to write your own handler.
--67618-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--67618-- Nevertheless we consider this a bug.  Please report
--67618-- it at http://valgrind.org/support/bug_reports.html.
==67618== Invalid read of size 8
==67618==    at 0x48F620B: g_strv_length (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x4C8E1D4: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4C8D026: gtk_application_set_accels_for_action (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x1267D7: maya_main_window_constructor (MainWindow.c:805)
==67618==    by 0x4A9626B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A98377: g_object_new_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A986CC: g_object_new (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x1261A8: maya_main_window_construct (MainWindow.c:274)
==67618==    by 0x1248B8: maya_application_init_gui (Application.c:496)
==67618==    by 0x124D18: maya_application_real_activate (Application.c:364)
==67618==    by 0x4A90A55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4AAFB27: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==  Address 0x1f79cbc8 is 0 bytes after a block of size 8 alloc'd
==67618==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==67618==    by 0x48D9D10: g_malloc0 (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x49CEEDF: ??? (in /usr/lib/x86_64-linux-gnu/libgee-0.8.so.2.6.1)
==67618==    by 0x4A06681: ??? (in /usr/lib/x86_64-linux-gnu/libgee-0.8.so.2.6.1)
==67618==    by 0x1267A9: maya_main_window_constructor (MainWindow.c:802)
==67618==    by 0x4A9626B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A98377: g_object_new_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A986CC: g_object_new (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x1261A8: maya_main_window_construct (MainWindow.c:274)
==67618==    by 0x1248B8: maya_application_init_gui (Application.c:496)
==67618==    by 0x124D18: maya_application_real_activate (Application.c:364)
==67618==    by 0x4A90A55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618== 
==67618== Conditional jump or move depends on uninitialised value(s)
==67618==    at 0xAE02988: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0xADE5F82: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0xADA067C: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0x5E4CE1F: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E937B0: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E8385E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E842C2: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E851A1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E4026D: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E52168: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E913A5: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E48704: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618== 
==67618== Conditional jump or move depends on uninitialised value(s)
==67618==    at 0xAE02771: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0xADE5F82: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0xADA067C: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.38.4)
==67618==    by 0x5E4CE1F: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E937B0: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E8385E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E842C2: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E84F3C: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E4015E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E52131: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E91246: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618==    by 0x5E48301: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==67618== 
==67618== Conditional jump or move depends on uninitialised value(s)
==67618==    at 0x2292C13E: ??? (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.47.0)
==67618==    by 0x22922595: rsvg_rust_handle_get_pixbuf_sub (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.47.0)
==67618==    by 0x22802485: ??? (in /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so)
==67618==    by 0x5433AA2: gdk_pixbuf_loader_close (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==67618==    by 0x5430232: ??? (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==67618==    by 0x543124E: gdk_pixbuf_new_from_stream_at_scale (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.4000.0)
==67618==    by 0x4D84718: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4D87A97: gtk_icon_info_load_icon (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4D80D11: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4D81437: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4D81553: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618==    by 0x4D8169F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.16)
==67618== 
==67618== Invalid read of size 8
==67618==    at 0x486F66C: __lambda11_ (EventStore.c:3006)
==67618==    by 0x486F66C: ___lambda11__gfunc (EventStore.c:3116)
==67618==    by 0x48F3A8F: g_slist_foreach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x486E1C2: calendar_event_store_on_objects_modified (EventStore.c:3174)
==67618==    by 0x486E1C2: ___lambda10_ (EventStore.c:2182)
==67618==    by 0x486E1C2: ____lambda10__e_cal_client_view_objects_modified (EventStore.c:2190)
==67618==    by 0x4A93DB2: g_cclosure_marshal_VOID__POINTERv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A90A55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4AAFB27: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4AB00D2: g_signal_emit (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x565CEFF: ??? (in /usr/lib/x86_64-linux-gnu/libecal-2.0.so.1.0.0)
==67618==    by 0x48D3E6D: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x48D421F: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x48D42C2: g_main_context_iteration (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x552DFD4: g_application_run (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.6400.6)
==67618==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==67618== 
==67618== 
==67618== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==67618==  Access not within mapped region at address 0x0
==67618==    at 0x486F66C: __lambda11_ (EventStore.c:3006)
==67618==    by 0x486F66C: ___lambda11__gfunc (EventStore.c:3116)
==67618==    by 0x48F3A8F: g_slist_foreach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x486E1C2: calendar_event_store_on_objects_modified (EventStore.c:3174)
==67618==    by 0x486E1C2: ___lambda10_ (EventStore.c:2182)
==67618==    by 0x486E1C2: ____lambda10__e_cal_client_view_objects_modified (EventStore.c:2190)
==67618==    by 0x4A93DB2: g_cclosure_marshal_VOID__POINTERv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4A90A55: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4AAFB27: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x4AB00D2: g_signal_emit (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6)
==67618==    by 0x565CEFF: ??? (in /usr/lib/x86_64-linux-gnu/libecal-2.0.so.1.0.0)
==67618==    by 0x48D3E6D: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x48D421F: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x48D42C2: g_main_context_iteration (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.6)
==67618==    by 0x552DFD4: g_application_run (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.6400.6)
==67618==  If you believe this happened as a result of a stack
==67618==  overflow in your program's main thread (unlikely but
==67618==  possible), you can try to increase the size of the
==67618==  main thread stack using the --main-stacksize= flag.
==67618==  The main thread stack size used in this run was 8388608.
==67618== 
==67618== HEAP SUMMARY:
==67618==     in use at exit: 16,222,159 bytes in 187,427 blocks
==67618==   total heap usage: 1,022,572 allocs, 835,145 frees, 100,096,186 bytes allocated
==67618== 
==67618== LEAK SUMMARY:
==67618==    definitely lost: 89,272 bytes in 117 blocks
==67618==    indirectly lost: 56,943 bytes in 2,388 blocks
==67618==      possibly lost: 1,386,635 bytes in 5,004 blocks
==67618==    still reachable: 13,100,613 bytes in 169,351 blocks
==67618==                       of which reachable via heuristic:
==67618==                         length64           : 20,968 bytes in 292 blocks
==67618==                         newarray           : 2,928 bytes in 103 blocks
==67618==         suppressed: 0 bytes in 0 blocks
==67618== Rerun with --leak-check=full to see details of leaked memory
==67618== 
==67618== Use --track-origins=yes to see where uninitialised values come from
==67618== For lists of detected and suppressed errors, rerun with: -s
==67618== ERROR SUMMARY: 28 errors from 5 contexts (suppressed: 2 from 2)
Violació de segment

Also I've installed all calendar packages with dbgsym (maya-calendar-plugin-google-dbgsym maya-calendar-plugin-caldav-dbgsym maya-calendar-dbgsym maya-calendar-daemon-dbgsym libmaya-calendar0-dbgsym) Do you need someone more??? I've not found an io.elementary.calendar-dbgsym package.

**Comment by mcclurgm** [comment]
That looks like that has all we need, thanks very much! I'll take a look and see what I can find.
